services:

  ##############################################################
  # messaging-app-client
  ##############################################################
  messaging-app-client:
    image: docker.io/library/messaging-app-client:v1.0
    container_name: messaging-app-client
    hostname: messaging-app-client
    ports:
      - "3000:3000"
    environment:
      APP_HOST: messaging-app

  ##############################################################
  # messaging-app
  ##############################################################
  messaging-app:
    image: messaging-app/messaging-app:0.0.1-SNAPSHOT
    container_name: messaging-app
    hostname: messaging-app
    ports:
      - "8000:8000"
    depends_on:
      - kafka
    environment:
      HMS_KAFKA_HOST: kafka
      HMS_KAFKA_PORT: 9092
      _JAVA_OPTIONS: >
        -Xdebug
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
  ##############################################################
  # ZOOKEEPER-KAFKA
  ##############################################################
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://192.168.1.68:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://192.168.1.68:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    restart: always
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: 192.168.1.68:2181